# Generated by Django 3.0.1 on 2020-01-02 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gram', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='comments',
            field=models.ManyToManyField(default=False, related_name='comment', to='gram.Profile'),
        ),
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(blank=True, default=False, related_name='likes', to='gram.Profile'),
        ),
    ]
