# Generated by Django 3.0.2 on 2020-01-04 14:07

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('gram', '0002_auto_20200104_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='comments',
            field=tinymce.models.HTMLField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='caption',
            field=tinymce.models.HTMLField(null=True),
        ),
    ]
