# Generated by Django 2.0 on 2020-01-05 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gram', '0004_auto_20200105_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_photo',
            field=models.ImageField(default='fur.jpg', upload_to='profile_pics'),
        ),
    ]
