# Generated by Django 3.0.1 on 2020-01-02 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gram', '0002_auto_20191223_1101'),
        ('gram', '0005_auto_20200102_1820'),
    ]

    operations = [
    ]
