# Generated by Django 3.0.1 on 2020-01-02 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gram', '0006_merge_20200102_1836'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='profile_image',
            new_name='profile_picture',
        ),
        migrations.AddField(
            model_name='post',
            name='comments',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.TextField(null=True),
        ),
    ]
