# Generated by Django 3.0.1 on 2020-01-02 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gram', '0008_auto_20200102_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='comments',
            field=models.TextField(null=True),
        ),
    ]
