# Generated by Django 3.0.1 on 2020-01-02 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gram', '0009_post_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.TextField(null=True),
        ),
    ]
